version: '2.2'

services:

  nginx:
    image: nginx:latest
    env_file: .env
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html
      - ./nginx/log:/var/log/nginx
    links:
      - php

  php:
    build: ./images/php_dev
    volumes:
      - ./app:/var/www/html
    links:
      - mariadb
      - nginx_test
      - nginx_test_ext

  mariadb:
    image: mariadb:latest
    ports:
      - "3366:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  nginx_test:
    image: nginx:latest
    env_file: .env
    ports:
    - "${WEBSERVER_TEST1_PORT}:80"
    volumes:
    - ./nginx_test/conf.d:/etc/nginx/conf.d
    - ./nginx_test/sites:/var/www
    - ./nginx_test/log:/var/log/nginx

  nginx_test_ext:
    image: nginx:latest
    env_file: .env
    ports:
    - "${WEBSERVER_TEST2_PORT}:80"
    volumes:
    - ./nginx_test_ext/conf.d:/etc/nginx/conf.d
    - ./nginx_test_ext/sites:/var/www
    - ./nginx_test_ext/log:/var/log/nginx